// =============================================================================
// weight_rom_bank.sv  —  Unified Weight + Bias BRAM ROM
// =============================================================================
// Two single-port BRAMs:
//   1. weight_rom  — 2,290,288 × INT8  (2.24 MB), read port 8b × 32b address
//   2. bias_rom    —     8,976 × INT32 (35 KB),   read port 32b × 14b address
//
// Initialization files:
//   weight_rom: hwconst/mem/weights_all.mem   (generated by scripts/gen_weight_rom.py)
//   bias_rom:   hwconst/mem/biases_all.mem    (generated by scripts/gen_weight_rom.py)
//
// The layer scheduler provides:
//   w_addr  — byte address into the unified weight ROM
//   b_addr  — index into the bias ROM
//   w_rd_en — enable weight read
//   b_rd_en — enable bias read
//
// Read latency: 1 clock cycle (registered output, BRAM READ_FIRST mode).
// Width scaling: the scheduler issues CIN_PAR×COUT_PAR consecutive reads
// per compute cycle.  For wide-fetch efficiency the ROM is implemented with
// a native 8-bit port; upper layers mux consecutive bytes into the weight_bus.
// =============================================================================

`timescale 1ns/1ps
import yolov10n_pkg::*;

module weight_rom_bank #(
  // Override paths for simulation; synthesis uses .coe files
  parameter string WEIGHT_MEM_FILE = "hwconst/mem/weights_all.mem",
  parameter string BIAS_MEM_FILE   = "hwconst/mem/biases_all.mem"
)(
  input  logic        clock,

  // ---- Weight ROM port -------------------------------------------------------
  input  logic [21:0] w_addr,    // byte address (0 .. WEIGHT_ROM_DEPTH-1)
  input  logic        w_rd_en,
  output logic  [7:0] w_data,    // one INT8 weight per cycle

  // ---- Bias ROM port ---------------------------------------------------------
  input  logic [13:0] b_addr,    // INT32 index (0 .. BIAS_ROM_DEPTH-1)
  input  logic        b_rd_en,
  output logic [31:0] b_data     // one INT32 bias per cycle
);

  // ---------------------------------------------------------------------------
  // Weight ROM  —  inferred as RAMB36E1 (8-bit port, ~560 instances)
  // Vivado Block RAM inference requires the array to be in an always block.
  // ---------------------------------------------------------------------------
  (* rom_style = "block" *)
  logic [7:0] weight_rom [0:WEIGHT_ROM_DEPTH-1];

  initial begin
    $readmemh(WEIGHT_MEM_FILE, weight_rom);
  end

  always_ff @(posedge clock) begin
    if (w_rd_en)
      w_data <= weight_rom[w_addr];
  end

  // ---------------------------------------------------------------------------
  // Bias ROM  —  inferred as RAMB18E1 (32-bit port, ~3 instances)
  // ---------------------------------------------------------------------------
  (* rom_style = "block" *)
  logic signed [31:0] bias_rom [0:BIAS_ROM_DEPTH-1];

  initial begin
    $readmemh(BIAS_MEM_FILE, bias_rom);
  end

  always_ff @(posedge clock) begin
    if (b_rd_en)
      b_data <= bias_rom[b_addr];
  end

endmodule : weight_rom_bank
